language: python
python:
    - "3.4"
    - "3.5"
install: "pip install -r requirements.txt"
script: nosetests --with-coverage --cover-package=TwitterCLI
after_success:
    - bash <(curl -s https://codecov.io/bash)
