language: python
python:
    - "3.4"
    - "3.5"
install: "pip install -r requirements.txt"
script: py.test --cov=TwitterCLI --cov=TweetSource tests/
after_success:
    - bash <(curl -s https://codecov.io/bash)
