twitter-cli:
    build: .
    command: python -u ./main.py
    ports:
        - "5000:5000"
    volumes:
        - .:/app
    links:
        - db

db:
    image: mongo:3.0
    ports:
        - "27017:27017"
    volumes_from:
        - mongo_data
    command: --smallfiles

mongo_data:
    image: mongo:3.0
    volumes:
        - /data/db
